load '6formation_results.mat'


k = 0.5;

%% statistics position error, include x, y and z
absPositionError = sum(abs(get(thtraj1, 'XData')-get(ehtraj1, 'XData'))+abs(get(thtraj1, 'YData')-get(ehtraj1, 'YData'))+abs(get(thtraj1, 'ZData')-get(ehtraj1, 'ZData')) ...
    +abs(get(thtraj2, 'XData')-get(ehtraj2, 'XData'))+abs(get(thtraj2, 'YData')-get(ehtraj2, 'YData'))+abs(get(thtraj2, 'ZData')-get(ehtraj2, 'ZData')) ...
    +abs(get(thtraj3, 'XData')-get(ehtraj3, 'XData'))+abs(get(thtraj3, 'YData')-get(ehtraj3, 'YData'))+abs(get(thtraj3, 'ZData')-get(ehtraj3, 'ZData')) ...
    +abs(get(thtraj4, 'XData')-get(ehtraj4, 'XData'))+abs(get(thtraj4, 'YData')-get(ehtraj4, 'YData'))+abs(get(thtraj4, 'ZData')-get(ehtraj4, 'ZData')) ...
    +abs(get(thtraj5, 'XData')-get(ehtraj5, 'XData'))+abs(get(thtraj5, 'YData')-get(ehtraj5, 'YData'))+abs(get(thtraj5, 'ZData')-get(ehtraj5, 'ZData')) ...
    +abs(get(thtraj6, 'XData')-get(ehtraj6, 'XData'))+abs(get(thtraj6, 'YData')-get(ehtraj6, 'YData'))+abs(get(thtraj6, 'ZData')-get(ehtraj6, 'ZData'))); % 1.2014e+03


%% statistics speed error, include x and y 
absSpeedError = sum(abs(get(ehvx1, "YData")-get(thvx1, "YData"))+abs(get(ehvy1, "YData")-get(thvy1, "YData")) ...
    +abs(get(ehvx2, "YData")-get(thvx2, "YData"))+abs(get(ehvy2, "YData")-get(thvy2, "YData")) ...
    +abs(get(ehvx3, "YData")-get(thvx3, "YData"))+abs(get(ehvy3, "YData")-get(thvy3, "YData")) ...
    +abs(get(ehvx4, "YData")-get(thvx4, "YData"))+abs(get(ehvy4, "YData")-get(thvy4, "YData")) ...
    +abs(get(ehvx5, "YData")-get(thvx5, "YData"))+abs(get(ehvy5, "YData")-get(thvy5, "YData")) ...
    +abs(get(ehvx6, "YData")-get(thvx6, "YData"))+abs(get(ehvy6, "YData")-get(thvy6, "YData"))); %  2.4128e+03


finalPoint = k*(absPositionError + absSpeedError) / 100 + (1-k) * time;
disp(['your performance score is: ' , num2str(finalPoint)]);    %27.9835
